---
  header_logo_url: /images/Logo1.png
  header_logo_text: Syrphidae of Italy (SoI)
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
    
    - label: Addition
      submenu:
        - label: Taxa Addition
          link: /newtaxa
        - label: Reference Addition
          link: /newreferences

    - label: Bibliography
      link: /resources/tw/filter/bibliography

    - label: Search DwC
      link: /resources/tw/filter/dwc_otus
    
    - label: Taxa
      link: /taxa